const Questions = [
"Wat is je favoriete feestdag van het jaar?",
"Wat is de 1 van de eerste herinneringen die je hebt?",
"Wat is je leuktste herinnering aan de basisschool?",
"Wat is de leukste herinnering van de middelbare?",
"Wat wilde je worden toen je heel jong was?",
"Wat is nog een land dat je wil bezoeken?",
"wat is je favoriete dier en waarom?",
"Hoe ziet je ideale vakantie eruit?",
"Wat is nog een geheim talent dat je hebt?",
"Welke sport deed je toen je klein was?",
"Welke sport/en doe je nu?",
"Wat is het eerste dat je doet als je thuis komt?",
"Hoe zag je kinderfeesje er vroeger uit?",
"Wie is de zon in jouw leven?",
"Wat is je meest bizarre trein verhaal?",
"Wat is het domste wat je ooit hebt gedaan?",
"Wie is je celebrity crush?",
"Ben je meer een moederskind of vadersmoederskind",
"Heb je een huisdier?",
"Wat staat er bovenaan je bucketlist?",
"Waar ben je het meest trots op?",
"Wat is de raarste droom ooit die jij hebt gehad?",
"Wat is je droom auto/huis?",
"Hoe zou je jezelf in één zin omschrijven?",
"Wat is jouw spaardoel?",
"Welke superkracht zou jij willen hebben?",
"Wat is je meest dierbare herinnering?",
"Wat is je lievelingsnummer?",
"Met wat zou je niet kunnen overleven?",
"Wat maakt iemand jouw beste vriend / vriendin?",
"Kunnen online-vrienden ook echte vrienden zijn?",
"Wie is/was je jeugdidool?",
"Waarin wil jij nog groeien?",
"Hoe wil jij herinnerd worden?",
"Stel dat niks illegaal is voor één dag, wat zou jij doen?",
"Wat is jouw 'guilty-pleasure' qua eten?",
"Wie bewonder je?",
"Wat facineert jou?",
"Stel dat je iets aan jezelf kan veranderen, wat zou dat zijn?",
"Waar droom jij over?",
"Wat is iets dat je hebt gedaan en nog steeds spijt van hebt?",
"Hoe lang zou jij zonder sociale media kunnen?",
]
function myQuestion() {
    const randomElement = Questions[Math.floor(Math.random() * Questions.length)];
    console.log(randomElement);  
    return randomElement;
}
module.exports = {myQuestion};

